services:
  solr:
    image: solr:9.4.0
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - ./config:/config
      - ./config/data:/opt/solr/data
      - ./config/scripts:/scripts
    environment:
      - SOLR_CORE_NAME=${SOLR_CORE_NAME:-mycore}
    command: bash /scripts/entrypoint.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/cores?action=STATUS"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: "no"
    networks:
      - search-net

  opensearch: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: public.ecr.aws/opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch
    security_opt:
      - no-new-privileges
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch # Name the node that will run in this container
      - discovery.seed_hosts=opensearch # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=false # Disable JVM heap memory swapping
      - plugins.security.disabled=true # Disable security plugin
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}    # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and later
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - "9200:9200" # REST API
      - "9600:9600" # Performance Analyzer
    networks:
      - search-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - "OPENSEARCH_ALLOW_INSECURE=true"
    networks:
      - search-net
    depends_on:
      - opensearch
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

volumes:
  opensearch-data:
  solr_data:


networks:
  search-net:
    driver: bridge
